### PR TITLE
Archiving & Restructure the folders 

### PR DESCRIPTION
**Pull request by ioana-chiorean**

### CODE REVIEW

**Comment by mitio** [comment]
Let's ping @oana-sipos as someone from the current webdev team to take a look and merge if needed 🔨

**Comment by oana-sipos** [comment]
Will do it ASAP, during the day.

**Comment by oana-sipos** [comment]
@ioana-chiorean Can you please rename România to Romania? We should keep the folder structure in English, even if the documents are in Romanian. Thanks!

**Comment by ioana-chiorean** [comment]
Done 👍

**Pull request merged**
